### ISSUE TITLE
1주차: JVM은 무엇이며, 자바 프로그램은 어떻게 실행되는가

### ISSUE THREAD

**Issue by awesomeo184** [awesomeo184/java-study#1]
## 목표
* 자바 소스 파일(.java)을 JVM으로 실행하는 과정 이해하기.

## 학습할 것
* JVM이란 무엇인가
* 컴파일 하는 방법
* 실행하는 방법
* 바이트코드란 무엇인가
* JIT 컴파일러란 무엇이며 어떻게 동작하는지
* JVM 구성 요소
* JDK와 JRE의 차이

대부분의 자바 기본서 인트로에 나오는 내용입니다. 깊게 파고 들어가면 한 없이 파고들 수 있는 부분이라서, 최소한 자바 소스 파일이 어떤 과정을 거쳐서 실행되는지 간략히 설명할 수 있을 정도로 공부하시면 될 것 같습니다. 물론 깊게 파고 들어가는 것은 본인 자유입니다.

**Comment by Jugiter** [comment]
목표

자바 소스 파일(.java)을 JVM으로 실행하는 과정 이해하기

​

학습할 것

JVM이란 무엇인가

컴파일 하는 방법

실행하는 방법

바이트코드란 무엇인가

JIT 컴파일러란 무엇이며 어떻게 동작하는지

JVM 구성 요소

JDK와 JRE의 차이

​

내용

1. JVM은 무엇인가

Java virtual Machine의 약자로 해석하자면 자바를 실행하기 위한 가상 컴퓨터라고 생각하면 된다. 

* 가상컴퓨터는 하드웨어로 생각되는 실제 컴퓨터가 아닌 소프트웨어로 구현된 컴퓨터이다. 컴퓨터속의 컴퓨터.

자바로 작성된 어플리케이션은 JVM이라는 가상컴퓨터에서만 작동한다. 따라서 자바 어플리케이션의 실행을 위해서는 JVM이 필수적인 것이다. 

일반 어플리케이션은 하드웨어로 전달되기 위해서는 OS만 거치면 되지만, 자바 어플리케이션은 OS와 JVM을 모두 거쳐야한다. 또한, 이는 하드웨어에 완전히 맞추어져서 컴파일된 상태가 아니기 때문에 속도가 느리다는 단점이 있다. (사용 시에 interpret됨)


* 자바 어플리케이션과 일반 어플리케이션의 하드웨어 전달과정 참고사진

하지만 위 그림과 같이 일반 어플리케이션은 OS와 바로 연결되어 있기 때문에 OS종속적이기 때문에, 다른 OS에서의 사용을 위해서는 타OS에 맞추어 변경해야한다. 하지만 자바 어플리케이션은 JVM과만 상호작용하기 때문에 다른 OS에서도 프로그램의 변경 없이 사용 가능하다. (하지만 JVM은 OS 종속적이기 때문에 해당 OS에서 실행 가능한 JVM이 필요로 됨 >> 주요 OS용 JVM이 제공되고 있음)

​

2. 컴파일 하는 방법

javac.exe : 자바 컴파일러, 자바소스코드를 바이트코드로 컴파일

java.exe : 자바 인터프리터, 컴파일러가 생성한 바이트코드를 해석하고 실행

javap.exe : 역어셈블러, 컴파일된 클래스파일을 원래의 소스로 변환

​

프로그래밍 언어로 작성한 코드를 기계가 알아듣게 다른 언어로 옮기는 작업을 컴파일, 이러한 작업을 하는 프로그램을 컴파일러 compiler 라고 한다. 자바의 경우에는 코드가 바이트코드로 컴파일되어 실행된다.

​

폴더 > src > properties > location 경로 복사 > cmd 접속 > cd 복사한 경로 > javac 클래스명.java > java 클래스명

​

3. 실행하는 방법

java.exe 파일을 사용하여 바이트코드로 컴파일 된 .class 실행

단, 실행 시에는 소스 파일명의 확장자는 붙이지 않음

​

4. 바이트코드란 무엇인가

- JVM이 이해할 수 있는 기계어 (JVM은 바이트코드를 다시 해당 OS의 기계어로 변환하여 OS로 전달)

- 특정 하드웨어가 아닌 가상 컴퓨터에서 돌아가는 실행 프로그램을 위한 이진 표현법

​

5. JIT 컴파일러란 무엇이며 어떻게 동작하는지

런타임시 Java 애플리케이션의 성능을 향상시키는 Java Runtime Environment의 구성 요소

Just-In-Time Compiler의 약자로 사용할 때 컴파일 한다는 의미로 실행엔진 내부에서 동작한다. 자바에서 complie을 하면 바이트코드로 변환되는데 JVM이 바이트코드를 기계어로 interpret 할 때 반복되는 내용은 컴파일을 통해 사용하고, 이 과정을 JIT 컴파일링이라고 한다. 이를 사용하면 반복 작업을 할 때 컴파일 없이 interpret만 하는 경우보다 더 높은 성능을 낼 수 있다. JIT 컴파일러는 반복되어 사용되는 코드나 기계어로 변환 시 많은 리소스가 필요한 부분을 코드가 실행되는 과정(Just-In-Time)에 실시간으로 변환(기계어)하여 캐싱한다. 그래서 또 다시 호출되었을 때 인터프리터가 해석하는 것이 아니라 JIT 컴파일러가 기계어로 변환해놓은 캐시에서 꺼내서 사용하게 되는 것이다.

​

정리하자면 바이트코드(컴파일된 자바코드)를 하드웨어의 기계어로 바로 전환해주는 역할을 함으로써 JVM의 기능을 향상시켜 더 빠른 속도로 일을 수행하게 한다.


* JIT 컴파일러 참고 사진

출처: https://aroundck.tistory.com/1949 [돼지왕 놀이터]

출처: https://sowhat4.tistory.com/61 [Humbly]

​

6. JVM 구성 요소

1) 인터프리터

.class(바이트코드)를 해당 하드웨어의 환경에 맞게 변환하여 운영체제에 종속적인 상태를 종속적이지 않은 형태로 만들어주는 역할

​

2) 클래스 로더

컴파일러가 SSD 내부에 만든 .class 파일을 읽는 행위를 클래스 로드라고 함

​

3) 실행엔진(내부에 JIT 컴파일러)

클래스 로더에 존재하는 클래스를 읽으면서 static이 있는지 판단함. 만약 static이 붙은 클래스가 없다면 자바는 그대로 종료

​

4) 가비지 컬렉터

C/C++에서 개발자가 직접 메모리 관리를 했다면, 자바에서는 가비지 컬렉터를 통해 사용하지 않는 메모리를 자동으로 회수함

​

출처 : https://cbw1030.tistory.com/289

 
[Java] JVM은 무엇이며 자바 코드는 어떻게 실행하는 것인가
오늘의 포스팅 목표는 자바 소스 파일(.java)을 JVM으로 실행하는 과정을 이해하는 것입니다. 목차 1. JVM이란 무엇인가 2. 컴파일 하는 방법 3. 실행하는 방법 4. 바이트코드란 무엇인가 5. JIT 컴파일러란 무엇..

cbw1030.tistory.com

​

7. JDK와 JRE의 차이

JDK (Java Development Kit) : 자바개발도구

JDK = JRE + 개발에 필요한 실행파일 (javac.exe 등) 

즉, JDK가 JRE를 포함 (더 큰 범위)

JRE (Java Runtime Environment) : 자바실행환경 - 자바로 작성된 응용프로그램이 실행되기 위한 최소환경.

JRE = JVM + 클래스 라이브러리 (Java API)

​

출처 : 자바의 정석

**Comment by ghost** [comment]
1주차 스터디
JVM은 무엇이며, 자바 프로그램은 어떻게 실행되는가

https://blog.naver.com/ss_1634/222354649544

**Comment by awesomeo184** [comment]
https://awesomeo184.netlify.app/Java-Basic/how_java_program_works/

**Comment by awesomeo184** [comment]
https://awesomeo184.netlify.app/Java-Basic/how_java_program_works/

**Comment by sangmin7648** [comment]
https://velog.io/@sangmin7648/JVM%EC%9D%80-%EB%AC%B4%EC%97%87%EC%9D%B4%EB%A9%B0-%EC%9E%90%EB%B0%94-%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%A8%EC%9D%80-%EC%96%B4%EB%96%BB%EA%B2%8C-%EC%8B%A4%ED%96%89%EB%90%98%EB%8A%94%EA%B0%80

**Comment by iamjaewhan** [comment]
https://blog.naver.com/PostView.nhn?blogId=jaewhan232&Redirect=View&logNo=222356218837&categoryNo=8&isAfterWrite=true&isMrblogPost=false&isHappyBeanLeverage=true&contentLength=41379

**Comment by jun1378527** [comment]
https://blog.naver.com/gogo981004/222356600854

**Comment by JungTag** [comment]
늦게 올렸습니다. 죄송합니다 ㅠ
https://cotak.tistory.com/114
