### ISSUE TITLE
10주차 과제: 멀티스레드 프로그래밍

### ISSUE THREAD

**Issue by awesomeo184** [awesomeo184/java-study#10]
## 목표

자바의 멀티스레드 프로그래밍에 대해 학습합니다.

## 공부할 것
* Thread 클래스와 Runnable 인터페이스
* 쓰레드의 상태
* 쓰레드의 우선순위
* Main 쓰레드
* 동기화
* 데드락

**Comment by awesomeo184** [comment]
https://www.inflearn.com/course/%EC%9A%B4%EC%98%81%EC%B2%B4%EC%A0%9C-%EA%B3%B5%EB%A3%A1%EC%B1%85-%EC%A0%84%EA%B3%B5%EA%B0%95%EC%9D%98

운영체제 강의

**Comment by jun1378527** [comment]
https://blog.naver.com/gogo981004/222458224901

**Comment by awesomeo184** [comment]
https://wisdom-and-record.tistory.com/48

자바 5 이후로 추가된 멀티스레딩 관련 API는 글 끝에 짤막하게 정리만 했어요.
자세한 내용은 나중에 따로 정리해서 공유할게요. 저도 아직 공부가 부족하고 양도 방대한지라... 😭

**Comment by sangmin7648** [comment]
https://velog.io/@sangmin7648/JAVA-%EB%A9%80%ED%8B%B0%EC%8A%A4%EB%A0%88%EB%93%9C-%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%B0%8D

글 몇개 찾아서 공유해요!
스레드 생성, 종료, 대기, 병합에 대한 글 : https://pages.mtu.edu/~shene/NSF-3/e-Book/FUNDAMENTALS/thread-management.html
JVM이 스레드를 어떻게 구현하는지에 대한 글 : https://www.developer.com/design/an-introduction-to-jvm-threading-implementation/
