### ISSUE TITLE
11주차 과제: Enum

### ISSUE THREAD

**Issue by awesomeo184** [awesomeo184/java-study#11]
## 목표

자바의 열거형에 대해 학습하세요.

## 학습할 것

* enum 정의하는 방법
* enum이 제공하는 메소드 (values()와 valueOf())
* java.lang.Enum
* EnumSet

**Comment by iamjaewhan** [comment]
https://blog.naver.com/jaewhan232/222466010918

**Comment by awesomeo184** [comment]
https://wisdom-and-record.tistory.com/52

**Comment by ghost** [comment]
https://blog.naver.com/ss_1634/222466354001

**Comment by jun1378527** [comment]
https://blog.naver.com/PostView.naver?blogId=gogo981004&Redirect=View&logNo=222467397356&categoryNo=13&isAfterWrite=true&isMrblogPost=false&isHappyBeanLeverage=true&contentLength=41438

**Comment by sangmin7648** [comment]
- 열거형의 생성자에 대해 이해를 잘 못하겠어요!
https://velog.io/@sangmin7648/Java-enum
