### ISSUE TITLE
12주차 과제: 애노테이션

### ISSUE THREAD

**Issue by awesomeo184** [awesomeo184/java-study#12]
## 목표

자바의 애노테이션에 대해 학습하세요.

## 학습할 것 (필수)
* 애노테이션 정의하는 방법
* @retention
* @target
* @documented
* 애노테이션 프로세서

**Comment by awesomeo184** [comment]
https://wisdom-and-record.tistory.com/54?category=907462

애너테이션 프로세서를 직접 작성해보고 싶으신 분들은 아래 글이 도움될 것 같습니다.
http://hannesdorfmann.com/annotation-processing/annotationprocessing101/

**Comment by JungTag** [comment]
https://cotak.tistory.com/163

**Comment by sangmin7648** [comment]
https://velog.io/@sangmin7648/%EC%95%A0%EB%84%88%ED%85%8C%EC%9D%B4%EC%85%98

**Comment by iamjaewhan** [comment]
https://blog.naver.com/jaewhan232/222476548279

**Comment by ghost** [comment]
https://blog.naver.com/ss_1634/222476598038
