### ISSUE TITLE
13주차 과제: I/O

### ISSUE THREAD

**Issue by awesomeo184** [awesomeo184/java-study#13]
## 목표

자바의 Input과 Ontput에 대해 학습하세요.

## 학습할 것 (필수)

* 스트림 (자바8 Stream API 아님!) / 버퍼 (Buffer) / 채널 (Channel) 기반의 I/O 
* InputStream과 OutputStream
* Byte와 Character 스트림
* 표준 스트림 (System.in, System.out, System.err)
* 파일 읽고 쓰기

**Comment by sangmin7648** [comment]
https://velog.io/@sangmin7648/Java-IO

**Comment by iamjaewhan** [comment]
https://blog.naver.com/jaewhan232/222484501701

**Comment by ghost** [comment]
https://blog.naver.com/ss_1634/222484040520

**Comment by awesomeo184** [comment]
https://wisdom-and-record.tistory.com/59?category=907462
