### ISSUE TITLE
2주차: 자바 데이터 타입, 변수 그리고 배열

### ISSUE THREAD

**Issue by awesomeo184** [awesomeo184/java-study#2]
## 목표

자바의 프리미티브 타입, 변수 그리고 배열을 사용하는 방법을 익힙니다.

## 학습할 것
* 프리미티브 타입 종류와 값의 범위 그리고 기본 값
* 프리미티브 타입과 레퍼런스 타입
* 리터럴
* 변수 선언 및 초기화하는 방법
* 변수의 스코프와 라이프타임
* 타입 변환, 캐스팅 그리고 타입 프로모션
* 1차 및 2차 배열 선언하기
* 타입 추론, var

❗️링크 올리면서 회의때 이야기해보면 좋을 것 같은 주제 혹은 잘 이해가 안되었던 내용을 같이 올려주세요!

**Comment by awesomeo184** [comment]
https://awesomeo184.netlify.app/Java-Basic/Java_DataType/

이 부분 공부하면서 처음 알게된건데요. 공부차원에서 퀴즈로 내볼게요.ㅎ 변수의 스코프와 관련된 내용입니다.

다음 두 코드는 각각 어떤 결과를 보여줄까요?

```java
public class Variable {
    public static void main(String[] args) {
    
        int i = 3;
        System.out.println(i);
        for (int i = 0; i < 10; i++) {
            System.out.println(i);
        }
    }
}
```

```java
public class Variable {
    public static void main(String[] args) {
    
        for (int i = 0; i < 3; i++) {
            System.out.println(i);
        }
        int i = 3;
        System.out.println(i);
    }
}
```

**Comment by jun1378527** [comment]
https://blog.naver.com/gogo981004/222367116808
저 준기 입니당

**Comment by sangmin7648** [comment]
https://velog.io/@sangmin7648/%EC%9E%90%EB%B0%94-%EB%8D%B0%EC%9D%B4%ED%84%B0-%ED%83%80%EC%9E%85-%EB%B3%80%EC%88%98-%EA%B7%B8%EB%A6%AC%EA%B3%A0-%EB%B0%B0%EC%97%B4

**Comment by ghost** [comment]
https://blog.naver.com/ss_1634/222369140216

**Comment by JungTag** [comment]
변수의 스코프와 라이프 타임은 아직 공부가 부족해서 추후 보충하도록 하겠습니다.
https://cotak.tistory.com/119

**Comment by iamjaewhan** [comment]
https://blog.naver.com/jaewhan232/222368604557
