### ISSUE TITLE
4주차: 제어문

### ISSUE THREAD

**Issue by awesomeo184** [awesomeo184/java-study#4]
## 목표

자바가 제공하는 제어문을 학습하세요.

## 학습할 것

선택문
반복문

**Comment by sangmin7648** [comment]
https://velog.io/@sangmin7648/%EC%A0%9C%EC%96%B4%EB%AC%B8
이번주의 주제는 아니지만 객체지향 수업 때 다뤘던 객체의 업캐스팅과 다운캐스팅이 어떤 상황에서 사용되는지 이해 못해 질문하고자 합니다!

**Comment by awesomeo184** [comment]
https://awesomeo184.netlify.app/Java-Basic/Control_of_Flow/

저도 이번주는 문법적인 사항에 대해 딱히 의문점이 생기는 것은 없네요.

다만 선택문에서 눈여겨볼 만한 내용이 있어 소개합니다.

<소트웍스 엔솔로지>라는 에세이에 '객체지향 생활체조'라는 객체지향 훈련 지침이 있는데요, 9가지 규칙 중에 두 번째 규칙이 `else` 예약어를 사용하지 말라는 것입니다.

아래 블로그에 왜 else를 사용하지 않는 것이 좋은지 잘 설명이 되어있어 공유합니다.

https://woowacourse.github.io/javable/post/2020-07-29-dont-use-else/

**Comment by JungTag** [comment]
https://cotak.tistory.com/135

**Comment by iamjaewhan** [comment]
https://blog.naver.com/jaewhan232/222408907349

**Comment by awesomeo184** [comment]
```java

public class Main {

    public static void main(String[] args) {

        Repository repository = new MySQL(); //*

        Service service = new Service(repository);

        service.doSomething();

        //...
    }

}

class Service {

    private Repository repository;

    public Service(Repository repository) {
        this.repository = repository;
    }

    void doSomething() {

        // .. 어떤 서비스 로직

        repository.save();
    }
}

class Repository {

    void save() {

    }
}


class MySQL extends Repository{

    void save() {
        //...저장 로직
        System.out.println("SAVE TO MY SQL DB");
    }
    
    void methodInMySQL() {
        System.out.println("dis");
    }
}

class Oracle extends Repository{

    void save() {
        //...저장 로직
        System.out.println("SAVE TO ORACLE DB");
    }
}
```

**Comment by jun1378527** [comment]
https://blog.naver.com/gogo981004/222409234189
