### ISSUE TITLE
5주차 과제: 클래스

### ISSUE THREAD

**Issue by awesomeo184** [awesomeo184/java-study#5]
## 목표

자바의 클래스에 대해 학습하세요.

## 학습할 것 

* 클래스 정의하는 방법
* 객체 만드는 방법 (new 키워드 이해하기)
* 메소드 정의하는 방법
* 생성자 정의하는 방법
* this 키워드 이해하기

**Comment by sangmin7648** [comment]
https://velog.io/@sangmin7648/%ED%81%B4%EB%9E%98%EC%8A%A4
- 객체의 범위를 참조 변수는 어떻게 아나?

**Comment by jun1378527** [comment]
https://blog.naver.com/gogo981004/222414772221

**Comment by ghost** [comment]
https://blog.naver.com/ss_1634/222415942123

**Comment by awesomeo184** [comment]
https://awesomeo184.netlify.app/Java-Basic/class/

**Comment by iamjaewhan** [comment]
https://blog.naver.com/jaewhan232/222416641379

**Comment by JungTag** [comment]
https://cotak.tistory.com/147
