### ISSUE TITLE
6주차 과제: 상속

### ISSUE THREAD

**Issue by awesomeo184** [awesomeo184/java-study#6]
## 목표

자바의 상속에 대해 공부하세요.

## 공부할 것

* 자바 상속의 특징
* super 키워드
* 메소드 오버라이딩
* 다이나믹 메소드 디스패치 (Dynamic Method Dispatch)
* [optional] 더블 디스패치(Double Dispatch)
* 추상 클래스
* final 키워드 (optional. 유사 파이널)
* Object 클래스

탐구심이 있으신 분들은 더블 디스패치에 대해서도 공부해보세요. 쉽지 않은 내용이므로 이해가 안되시면 그냥 넘어가도 좋습니다.

참고할만한 영상을 공유합니다.

https://www.youtube.com/watch?v=s-tXAHub6vg

**Comment by awesomeo184** [comment]
상속
https://awesomeo184.netlify.app/Java-Basic/inheritance/

더블 디스패치
https://awesomeo184.netlify.app/The%20Java/double_dispatch/

**Comment by iamjaewhan** [comment]
https://blog.naver.com/jaewhan232/222423728609

**Comment by JungTag** [comment]
https://cotak.tistory.com/148

**Comment by jun1378527** [comment]
https://blog.naver.com/PostView.naver?blogId=gogo981004&Redirect=View&logNo=222424462081&categoryNo=13&isAfterWrite=true&isMrblogPost=false&isHappyBeanLeverage=true&contentLength=128538

**Comment by sangmin7648** [comment]
https://velog.io/@sangmin7648/%EC%83%81%EC%86%8D
궁금증들
- private 변수의 접근을 자식 클래스에서 어떻게 하는가? (super.get() ???)
- 다이나믹 메소드 디스패치가 중요한 이유는 클라이언트 --> 서플라이어 의존관계의 클라이언트 클래스의 재사용성을 높이기 위해서이다. 서플라이어를 클래스가 아닌 인터페이스로 하므로써 재사용성을 높일 수 있는데 List<Integer> list = new ArrayList<Integer>(); 처럼 흔히 인터페이스 참조변수로 사용하는 이유이기도 하다. (이렇게 이해했는데 맞나요?)
- 업캐스팅시 자식 클래스에만 있는 변수/메소드는 객체에 존재하는데 접근이 불가능한건가요 아니면 아예 삭제되나요?
