### ISSUE TITLE
7주차 과제: 패키지

### ISSUE THREAD

**Issue by awesomeo184** [awesomeo184/java-study#7]
# 목표

자바의 패키지에 대해 학습하세요.

# 공부할 것
* package 키워드
* import 키워드
* 클래스패스
* CLASSPATH 환경변수
* -classpath 옵션
* 접근지시자

**Comment by ghost** [comment]
https://blog.naver.com/ss_1634/222432453602

**Comment by awesomeo184** [comment]
https://wisdom-and-record.tistory.com/43?category=907462

**Comment by jun1378527** [comment]
https://blog.naver.com/PostView.naver?blogId=gogo981004&Redirect=View&logNo=222432553153&categoryNo=13&isAfterWrite=true&isMrblogPost=false&isHappyBeanLeverage=true&contentLength=81722

**Comment by JungTag** [comment]
https://cotak.tistory.com/149

아래는 인텔리제이에서 CLASSPATH를 추가하는 방법에 대해 설명된 글입니다.
https://vvshinevv.tistory.com/70

**Comment by iamjaewhan** [comment]
https://blog.naver.com/jaewhan232/222432737600

**Comment by sangmin7648** [comment]
https://velog.io/@sangmin7648/%ED%8C%A8%ED%82%A4%EC%A7%80
