### ISSUE TITLE
8주차 과제: 인터페이스

### ISSUE THREAD

**Issue by awesomeo184** [awesomeo184/java-study#8]
## 목표

자바의 인터페이스에 대해 학습하세요

## 공부할 것

* 인터페이스 정의하는 방법
* 인터페이스 구현하는 방법
* 인터페이스 레퍼런스를 통해 구현체를 사용하는 방법
* 인터페이스 상속
* 인터페이스의 기본 메소드 (Default Method), 자바 8
* 인터페이스의 static 메소드, 자바 8
* 인터페이스의 private 메소드, 자바 9

**Comment by JungTag** [comment]
- 추상클래스 vs 인터페이스의 차이점
https://myjamong.tistory.com/150

**Comment by ghost** [comment]
https://blog.naver.com/ss_1634/222439961175

**Comment by iamjaewhan** [comment]
https://blog.naver.com/jaewhan232/222438785047

**Comment by jun1378527** [comment]
https://blog.naver.com/gogo981004/222440998913

**Comment by sangmin7648** [comment]
https://velog.io/@sangmin7648/%EC%9D%B8%ED%84%B0%ED%8E%98%EC%9D%B4%EC%8A%A4

**Comment by JungTag** [comment]
https://cotak.tistory.com/154

**Comment by awesomeo184** [comment]
https://wisdom-and-record.tistory.com/45?category=907462
