### ISSUE TITLE
9주차 과제: 예외처리

### ISSUE THREAD

**Issue by awesomeo184** [awesomeo184/java-study#9]
## 목표

자바의 예외 처리에 대해 학습하세요.

## 학습할 것

* 자바에서 예외 처리 방법 (try, catch, throw, throws, finally)
* 자바가 제공하는 예외 계층 구조
* Exception과 Error의 차이는?
* RuntimeException과 RE가 아닌 것의 차이는?
* 커스텀한 예외 만드는 방법

**Comment by awesomeo184** [comment]
https://wisdom-and-record.tistory.com/46

**Comment by iamjaewhan** [comment]
https://blog.naver.com/PostView.naver?blogId=jaewhan232&Redirect=View&logNo=222449773000&categoryNo=8&isAfterWrite=true&isMrblogPost=false&isHappyBeanLeverage=true&contentLength=37956

**Comment by jun1378527** [comment]
https://blog.naver.com/gogo981004/222449831438

**Comment by ghost** [comment]
https://blog.naver.com/ss_1634/222449685704

**Comment by JungTag** [comment]
https://cotak.tistory.com/155
